import os
import json
import tempfile
import pandas as pd
import yfinance as yf
from datetime import datetime
from indicators import calculate_indicators
import warnings

warnings.filterwarnings('ignore')

CACHE_DIR = "data/ohlcv_cache"
OUTPUT_FILE = "data/latest_screener_results.json"

def get_market_regime() -> bool:
    """Checks if Nifty 50 is above its 50 EMA today for the market regime filter."""
    try:
        nifty = yf.download("^NSEI", period="1y", progress=False)
        if isinstance(nifty.columns, pd.MultiIndex):
            nifty.columns = nifty.columns.get_level_values(0)
        
        nifty['EMA_50'] = nifty['Close'].ewm(span=50, adjust=False).mean()
        latest_close = float(nifty['Close'].iloc[-1])
        latest_ema = float(nifty['EMA_50'].iloc[-1])
        
        return latest_close > latest_ema
    except Exception as e:
        print(f"Warning: Failed to fetch market regime: {e}")
        return True  # Fail open if yfinance rate limits

def evaluate_signals(ticker: str, df: pd.DataFrame, is_market_bullish: bool) -> dict:
    """Evaluates technical rules, applies disqualifiers, and calculates 0-6 score."""
    if df.empty or len(df) < 200:
        return None

    # Calculate indicators (includes MACD from indicators.py)
    df = calculate_indicators(df)

    latest = df.iloc[-1]
    prev = df.iloc[-2]

    # Handle scalar conversion safely
    close_price = float(latest['Close'])
    prev_close = float(prev['Close'])
    ema_50 = float(latest['EMA_50']) if pd.notna(latest['EMA_50']) else None
    ema_200 = float(latest['EMA_200']) if pd.notna(latest['EMA_200']) else None
    prev_ema_200 = float(prev['EMA_200']) if pd.notna(prev['EMA_200']) else None
    rsi_14 = float(latest['RSI_14']) if pd.notna(latest['RSI_14']) else None
    volume = float(latest['Volume'])
    vol_sma_20 = float(latest['VOL_SMA_20']) if pd.notna(latest['VOL_SMA_20']) else None

    # Dynamically find MACD columns generated by pandas-ta
    macd_col = next((c for c in df.columns if c.startswith('MACD_') and len(c.split('_')) == 4), None)
    macds_col = next((c for c in df.columns if c.startswith('MACDs_')), None)

    # ==========================================
    # DISQUALIFIERS
    # ==========================================
    # 1. Reject if extended >15% above the 50 EMA
    if ema_50:
        pct_above_50 = (close_price - ema_50) / ema_50
        if pct_above_50 > 0.15:
            return None 

    # 2. Reject if Market is Bearish
    if not is_market_bullish:
        return None

    # ==========================================
    # SCORING ENGINE (0-6)
    # ==========================================
    triggers = []
    score = 0

    # Point 1: Above 200 EMA
    if ema_200 and close_price > ema_200:
        triggers.append("ABOVE_EMA_200")
        score += 1
        
    # Point 2: Fresh 200 EMA Breakout (Bonus Conviction)
    if ema_200 and prev_ema_200 and close_price > ema_200 and prev_close <= prev_ema_200:
        triggers.append("EMA_200_BREAKOUT")
        score += 1

    # Point 3: Above 50 EMA (Trend Alignment)
    if ema_50 and close_price > ema_50:
        triggers.append("ABOVE_EMA_50")
        score += 1

    # Point 4: Volume Spike (>2x)
    if vol_sma_20 and volume > (2.0 * vol_sma_20):
        triggers.append("VOLUME_SPIKE_2X")
        score += 1

    # Point 5: RSI Goldilocks (Momentum > 60 but NOT overbought > 70)
    if rsi_14 and 60 < rsi_14 <= 70:
        triggers.append("RSI_60_TO_70")
        score += 1

    # Point 6: MACD Bullish Crossover
    if macd_col and macds_col:
        macd_line = float(latest[macd_col])
        macd_sig = float(latest[macds_col])
        prev_macd = float(prev[macd_col])
        prev_sig = float(prev[macds_col])
        
        if macd_line > macd_sig and prev_macd <= prev_sig:
            triggers.append("MACD_BULLISH_CROSS")
            score += 1

    # Output generation based on Score
    if score >= 3:
        # Split logic: Score 5-6 is Trade-Ready, 3-4 is Watchlist
        status = "Trade-Ready" if score >= 5 else "Watchlist"
        
        return {
            "ticker": ticker,
            "last_date": str(latest.name.date()) if hasattr(latest.name, 'date') else str(latest.name),
            "close": round(close_price, 2),
            "rsi_14": round(rsi_14, 2) if rsi_14 else None,
            "pct_above_50": round(pct_above_50 * 100, 2) if ema_50 else None,
            "volume_ratio": round(volume / vol_sma_20, 2) if vol_sma_20 else None,
            "score": score,
            "status": status,
            "triggers": triggers
        }

    return None

def run_screener():
    print("Checking Broader Market Regime...")
    is_market_bullish = get_market_regime()
    print(f"Nifty 50 Trend > 50 EMA: {'✅ Bullish' if is_market_bullish else '❌ Bearish (Filtering all longs)'}")

    if not is_market_bullish:
        print("Market is bearish. Screener will run but return 0 'Trade-Ready' setups to protect capital.")

    print("\nRunning technical screener across cached stocks...")
    results = []

    if not os.path.exists(CACHE_DIR):
        print("No cache directory found. Run data_fetcher.py first.")
        return

    cache_files = [f for f in os.listdir(CACHE_DIR) if f.endswith('.parquet')]

    for file in cache_files:
        ticker = file.replace('.parquet', '')
        filepath = os.path.join(CACHE_DIR, file)

        try:
            df = pd.read_parquet(filepath)
            signal = evaluate_signals(ticker, df, is_market_bullish)
            if signal:
                results.append(signal)
                print(f"[{signal['status']}] {ticker} | Score: {signal['score']}/6")
        except Exception as e:
            pass

    # Sort results so Trade-Ready and highest scores are at the top
    results = sorted(results, key=lambda x: x['score'], reverse=True)

    output_data = {
        "updated_at": datetime.now().isoformat(),
        "market_regime": "Bullish" if is_market_bullish else "Bearish",
        "total_scanned": len(cache_files),
        "total_signals": len(results),
        "signals": results
    }

    output_dir = os.path.dirname(OUTPUT_FILE)
    os.makedirs(output_dir, exist_ok=True)

    with tempfile.NamedTemporaryFile('w', dir=output_dir, delete=False) as tf:
        json.dump(output_data, tf, indent=2)
        temp_name = tf.name

    os.replace(temp_name, OUTPUT_FILE)
    print(f"\nScreener complete. Saved {len(results)} setups to {OUTPUT_FILE}")

if __name__ == "__main__":
    run_screener()
