name: Ping Streamlit App

on:
  schedule:
    - cron: '0 0,12 * * *' # Runs twice a day: at 00:00 and 12:00 UTC
  workflow_dispatch: # Allows you to manually trigger it anytime

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hit Streamlit URL
        run: |
          curl -s -I "https://screener101.streamlit.app"
